# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/olaniyi.adeoye@gmail.com/LHS Analtics Data Delivery")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT distinct * FROM lhsdataproject.silver.silver_patients where 1=1 "))



# COMMAND ----------


from pyspark.sql import functions as F
from pyspark.sql.functions import expr
from pyspark.sql.functions import to_timestamp


##def stg_silver_events():
df = spark.read.table("lhsdataproject.bronze.bronze_events")
df = df.withColumn( "EventDateTime",F.to_timestamp(F.col("EventDtTm"), "M/d/yyyy H:mm")).withColumn("bronze_Load_Datetime", F.current_timestamp())
df = df\
        .withColumn("EventDate", F.to_date("EventDateTime"))\
        .withColumn("EventTime", F.date_format("EventDateTime", "H:mm"))\
        .withColumn("Facility",  
                    expr("CASE WHEN EventType = 'Transfer' and EventNote LIKE '%/%/%' THEN trim(split(EventNote, '/')[0]) END"))\
        .withColumn("Building",
                    expr("CASE WHEN EventType = 'Transfer' and EventNote LIKE '%/%/%' THEN trim(split(EventNote, '/')[1]) END"))\
        .withColumn("Unit", 
                    expr("CASE WHEN EventType = 'Transfer' and EventNote LIKE '%/%/%' THEN trim(split(EventNote, '/')[2]) END"))\
        .withColumn("Species", 
                    expr("CASE WHEN EventType = 'Micro-Identification' and EventNote LIKE '%/%' THEN trim(split(EventNote, '/')[0]) END"))\
        .withColumn("Organism", 
                    expr("CASE WHEN EventType = 'Micro-Identification' and EventNote LIKE '%/%' THEN trim(split(EventNote, '/')[1]) END"))\
        .withColumn("TestResult",
                    expr("CASE WHEN EventType = 'Micro-Identification' and EventNote LIKE '%/%' THEN 'Positive'\
                            WHEN EventType = 'Micro-Identification' and EventNote IS NULL THEN 'Sample Clear' END"))\
        .withColumn("MicrobiologyTest", 
                    expr("CASE WHEN EventType in ('Micro-End', 'Micro-Start') THEN EventNote END"))\
        .withColumn("MedicalSpecialty",
                    expr("CASE WHEN EventType in ('Surg-End', 'Surg-Start') AND EventNote LIKE '%/%' THEN trim(split(EventNote, '/')[0]) END"))\
        .withColumn("SurgicalProcedure", 
                    expr("CASE WHEN EventType in ('Surg-End', 'Surg-Start') AND EventNote LIKE '%/%' THEN trim(split(EventNote, '/')[1]) END"))\
        .withColumn("DischargeStaff", 
                    expr("CASE WHEN EventType in ('Discharge') THEN EventStaff END"))\
        .withColumnRenamed("Visit", "VisitID")       
df = (
    df.select("VisitID", "EventType", "EventDate", "EventTime","PIN", "EventNote", "EventStaff", "Facility", "Building", "Unit", "Species", "Organism", "TestResult",   "MicrobiologyTest", "MedicalSpecialty", "SurgicalProcedure","DischargeStaff", "_rescued_data", "bronze_Load_Datetime")
    )

df = df.withColumn("LocationHashKey", F.sha2(F.concat_ws("||", "Facility", "Building", "Unit"), 256))
df = df.withColumn("ProcedureHashKey", F.sha2(F.concat_ws("||", "MedicalSpecialty", "SurgicalProcedure"), 256))
df = df.withColumn("OrganismHashKey", F.sha2(F.concat_ws("||", "Species", "Organism"), 256))
df = df.withColumn("MicrobiologyTestHashKey", F.sha2(F.concat_ws("||", "MicrobiologyTest"), 256))




df.display()




# COMMAND ----------

# MAGIC %sql
# MAGIC select * from lhsdataproject.silver.silver_patients

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC create table lhsdataproject.gold.DimPatients(
# MAGIC DimPatientID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC PIN varchar(20) NOT NULL,
# MAGIC FirstName VARCHAR(100),
# MAGIC LastName VARCHAR(100),
# MAGIC BirthDate Date,  
# MAGIC Sex Varchar(10),
# MAGIC Address varchar(200),
# MAGIC City varchar(100),
# MAGIC Province varchar(100),
# MAGIC PostalCode varchar(20),
# MAGIC PhoneNumber varchar(20),
# MAGIC Email varchar(200),
# MAGIC EmergencyContact varchar(200),
# MAGIC EmergencyPhone varchar(20),
# MAGIC RegistrationDate Date,
# MAGIC IsActive varchar(3),
# MAGIC LoadDatetime timestamp,
# MAGIC EffStartDatetime timestamp,
# MAGIC EffEndDatetime timestamp,
# MAGIC PRIMARY KEY(DimPatientID)
# MAGIC
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC drop table lhsdataproject.bronze.silver_events
# MAGIC
